# Generated by Django 4.2.1 on 2024-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_autotimeline_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='autotimeline',
            field=models.DateField(),
        ),
    ]
