# Generated by Django 4.2.1 on 2024-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_communityforum_studygroup_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='person',
        ),
        migrations.AddField(
            model_name='communityforum',
            name='subscribers',
            field=models.ManyToManyField(related_name='forum_subscriptions', to='tasks.userdata'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', to='tasks.userdata'),
        ),
    ]
