# Generated by Django 4.2.1 on 2024-05-23 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_userdata_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityforum',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
        migrations.AddField(
            model_name='communityforum',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
