# Generated by Django 4.2.1 on 2024-05-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_communityforum_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityforum',
            old_name='name',
            new_name='user_data',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='name',
            new_name='user_data',
        ),
    ]
