# Generated by Django 4.2.1 on 2024-05-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_communityforum_user_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityforum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='communityforum',
            name='person',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='person',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='person',
        ),
        migrations.AddField(
            model_name='communityforum',
            name='user_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.userdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='user_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.userdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
