# Generated by Django 4.2.1 on 2024-05-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_communityforum_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityforum',
            name='user_data',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='user_data',
        ),
    ]
