# Generated by Django 4.2.1 on 2024-05-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_communityforum_user_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityforum',
            name='user_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.userdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='user_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.userdata'),
            preserve_default=False,
        ),
    ]
